-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: tables-global_user_blocks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/global_user_blocks (
  gub_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  gub_address TINYBLOB NOT NULL,
  gub_central_user INT UNSIGNED DEFAULT 0 NOT NULL,
  gub_by_central_user BIGINT UNSIGNED NOT NULL,
  gub_reason VARBINARY(767) NOT NULL,
  gub_timestamp BINARY(14) NOT NULL,
  gub_auto TINYINT(1) DEFAULT 0 NOT NULL,
  gub_anon_only TINYINT(1) DEFAULT 0 NOT NULL,
  gub_create_account TINYINT(1) DEFAULT 1 NOT NULL,
  gub_enable_autoblock TINYINT(1) DEFAULT 1 NOT NULL,
  gub_expiry VARBINARY(14) NOT NULL,
  gub_deleted TINYINT(1) DEFAULT 0 NOT NULL,
  gub_block_email TINYINT(1) DEFAULT 0 NOT NULL,
  gub_allow_usertalk TINYINT(1) DEFAULT 0 NOT NULL,
  gub_parent_block_id INT UNSIGNED DEFAULT NULL,
  gub_sitewide TINYINT(1) DEFAULT 1 NOT NULL,
  UNIQUE INDEX gub_address_unique (
    gub_address(255),
    gub_central_user,
    gub_auto
  ),
  INDEX gub_central_user (gub_central_user),
  INDEX gub_timestamp (gub_timestamp),
  INDEX gub_expiry (gub_expiry),
  INDEX gub_parent_block_id (gub_parent_block_id),
  PRIMARY KEY(gub_id)
) /*$wgDBTableOptions*/;